//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Admin", typeof(Admin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Role.
        /// </summary>
        public static string CreateRole_BTN_Create {
            get {
                return ResourceManager.GetString("CreateRole_BTN_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string CreateRole_RoleName {
            get {
                return ResourceManager.GetString("CreateRole_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Role.
        /// </summary>
        public static string CreateRole_Title {
            get {
                return ResourceManager.GetString("CreateRole_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove users.
        /// </summary>
        public static string EditRole_BTN_AddOrRemove {
            get {
                return ResourceManager.GetString("EditRole_BTN_AddOrRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EditRole_BTN_Cancel {
            get {
                return ResourceManager.GetString("EditRole_BTN_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string EditRole_BTN_Update {
            get {
                return ResourceManager.GetString("EditRole_BTN_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users in role.
        /// </summary>
        public static string EditRole_NoUsers {
            get {
                return ResourceManager.GetString("EditRole_NoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users in this role.
        /// </summary>
        public static string EditRole_SubTitle {
            get {
                return ResourceManager.GetString("EditRole_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role.
        /// </summary>
        public static string EditRole_Title {
            get {
                return ResourceManager.GetString("EditRole_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string ListRoles_BTN_Create {
            get {
                return ResourceManager.GetString("ListRoles_BTN_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ListRoles_BTN_Delete {
            get {
                return ResourceManager.GetString("ListRoles_BTN_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ListRoles_BTN_Edit {
            get {
                return ResourceManager.GetString("ListRoles_BTN_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ListRoles_BTN_Search {
            get {
                return ResourceManager.GetString("ListRoles_BTN_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUPS.
        /// </summary>
        public static string ListRoles_Groups {
            get {
                return ResourceManager.GetString("ListRoles_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string ListRoles_Role {
            get {
                return ResourceManager.GetString("ListRoles_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for roles....
        /// </summary>
        public static string ListRoles_Search {
            get {
                return ResourceManager.GetString("ListRoles_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles &quot;User&quot; and &quot;Admin&quot; cannot be deleted as they are important for the application security.
        ///                You can add new roles but they don&apos;t have any functionality. In most cases it&apos;s a better idea to use.
        /// </summary>
        public static string ListRoles_SubDesc {
            get {
                return ResourceManager.GetString("ListRoles_SubDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Roles.
        /// </summary>
        public static string ListRoles_SubTitle {
            get {
                return ResourceManager.GetString("ListRoles_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Roles.
        /// </summary>
        public static string ListRoles_Title {
            get {
                return ResourceManager.GetString("ListRoles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string MODEL_CreateRole_RoleName {
            get {
                return ResourceManager.GetString("MODEL_CreateRole_RoleName", resourceCulture);
            }
        }
    }
}
