//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Certificates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Certificates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Certificates", typeof(Certificates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new certificate.
        /// </summary>
        public static string Create_New_Btn {
            get {
                return ResourceManager.GetString("Create_New_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate: This is the official name of the certificate. Please use the full name..
        /// </summary>
        public static string Create_SubDesc1 {
            get {
                return ResourceManager.GetString("Create_SubDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer: The organization granting the certificate. For example: Microsoft.
        /// </summary>
        public static string Create_SubDesc2 {
            get {
                return ResourceManager.GetString("Create_SubDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create_Submit {
            get {
                return ResourceManager.GetString("Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new certificate.
        /// </summary>
        public static string Create_Title {
            get {
                return ResourceManager.GetString("Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        public static string Delete_Skill {
            get {
                return ResourceManager.GetString("Delete_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Edit_BTN_Submit {
            get {
                return ResourceManager.GetString("Edit_BTN_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Name.
        /// </summary>
        public static string Edit_SkillName {
            get {
                return ResourceManager.GetString("Edit_SkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Certificate.
        /// </summary>
        public static string Edit_Title {
            get {
                return ResourceManager.GetString("Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Index_BTN_Create {
            get {
                return ResourceManager.GetString("Index_BTN_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Index_BTN_Delete {
            get {
                return ResourceManager.GetString("Index_BTN_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Index_BTN_Edit {
            get {
                return ResourceManager.GetString("Index_BTN_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Index_BTN_Search {
            get {
                return ResourceManager.GetString("Index_BTN_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for certifricates....
        /// </summary>
        public static string Index_Search {
            get {
                return ResourceManager.GetString("Index_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        public static string Index_Skill {
            get {
                return ResourceManager.GetString("Index_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate is a document serving as evidence of certain qualifications..
        /// </summary>
        public static string Index_SubDesc1 {
            get {
                return ResourceManager.GetString("Index_SubDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can add, edit, and delete certificates for users to choose from..
        /// </summary>
        public static string Index_SubDesc2 {
            get {
                return ResourceManager.GetString("Index_SubDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of certificates.
        /// </summary>
        public static string Index_SubTitle {
            get {
                return ResourceManager.GetString("Index_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        public static string MODEL_Name {
            get {
                return ResourceManager.GetString("MODEL_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer.
        /// </summary>
        public static string MODEL_Organization {
            get {
                return ResourceManager.GetString("MODEL_Organization", resourceCulture);
            }
        }
    }
}
