//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Courses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Courses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Courses", typeof(Courses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create_BTN_Create {
            get {
                return ResourceManager.GetString("Create_BTN_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        public static string Create_CourseName {
            get {
                return ResourceManager.GetString("Create_CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a description.
        /// </summary>
        public static string Create_Desc {
            get {
                return ResourceManager.GetString("Create_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Length (est. amount of lessons).
        /// </summary>
        public static string Create_Length {
            get {
                return ResourceManager.GetString("Create_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Location (City/Room/Organization/Online).
        /// </summary>
        public static string Create_Location {
            get {
                return ResourceManager.GetString("Create_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new course.
        /// </summary>
        public static string Create_Title {
            get {
                return ResourceManager.GetString("Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Lesson.
        /// </summary>
        public static string Index_BTN_AddLesson {
            get {
                return ResourceManager.GetString("Index_BTN_AddLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Members.
        /// </summary>
        public static string Index_BTN_AddMembers {
            get {
                return ResourceManager.GetString("Index_BTN_AddMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Index_BTN_Complete {
            get {
                return ResourceManager.GetString("Index_BTN_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Index_BTN_Details {
            get {
                return ResourceManager.GetString("Index_BTN_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Index_BTN_Edit {
            get {
                return ResourceManager.GetString("Index_BTN_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Index_BTN_Join {
            get {
                return ResourceManager.GetString("Index_BTN_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Index_BTN_Members {
            get {
                return ResourceManager.GetString("Index_BTN_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        public static string Index_CourseName {
            get {
                return ResourceManager.GetString("Index_CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string Index_Create {
            get {
                return ResourceManager.GetString("Index_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Index_Duration {
            get {
                return ResourceManager.GetString("Index_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attend.
        /// </summary>
        public static string Index_Lesson_Attend {
            get {
                return ResourceManager.GetString("Index_Lesson_Attend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attending.
        /// </summary>
        public static string Index_Lesson_Attending {
            get {
                return ResourceManager.GetString("Index_Lesson_Attending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Index_Lesson_Date {
            get {
                return ResourceManager.GetString("Index_Lesson_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson.
        /// </summary>
        public static string Index_Lesson_Lesson {
            get {
                return ResourceManager.GetString("Index_Lesson_Lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Index_Lesson_Location {
            get {
                return ResourceManager.GetString("Index_Lesson_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Index_Lesson_Members {
            get {
                return ResourceManager.GetString("Index_Lesson_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessons.
        /// </summary>
        public static string Index_Lessons {
            get {
                return ResourceManager.GetString("Index_Lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Index_Location {
            get {
                return ResourceManager.GetString("Index_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for courses....
        /// </summary>
        public static string Index_Search {
            get {
                return ResourceManager.GetString("Index_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Index_Status_Completed {
            get {
                return ResourceManager.GetString("Index_Status_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the course to view details..
        /// </summary>
        public static string Index_TitleDesc {
            get {
                return ResourceManager.GetString("Index_TitleDesc", resourceCulture);
            }
        }
    }
}
