//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CourseMembers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CourseMembers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CourseMembers", typeof(CourseMembers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Courses.
        /// </summary>
        public static string Index_BackCourse {
            get {
                return ResourceManager.GetString("Index_BackCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Index_BTN_Delete {
            get {
                return ResourceManager.GetString("Index_BTN_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Index_BTN_Details {
            get {
                return ResourceManager.GetString("Index_BTN_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Index_BTN_Edit {
            get {
                return ResourceManager.GetString("Index_BTN_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Index_BTN_Grade {
            get {
                return ResourceManager.GetString("Index_BTN_Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Index_Completed {
            get {
                return ResourceManager.GetString("Index_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed:.
        /// </summary>
        public static string Index_CompletedStatus {
            get {
                return ResourceManager.GetString("Index_CompletedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Index_Create {
            get {
                return ResourceManager.GetString("Index_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped out:.
        /// </summary>
        public static string Index_DroppedOut {
            get {
                return ResourceManager.GetString("Index_DroppedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrolled:.
        /// </summary>
        public static string Index_Enrolled {
            get {
                return ResourceManager.GetString("Index_Enrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Index_Grade {
            get {
                return ResourceManager.GetString("Index_Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently viewing your membership information. You are not an administrator, and can only see your personal information..
        /// </summary>
        public static string Index_NotAdmin {
            get {
                return ResourceManager.GetString("Index_NotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Index_Progress {
            get {
                return ResourceManager.GetString("Index_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Index_Status {
            get {
                return ResourceManager.GetString("Index_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -course. You can view, edit, and delete members from the course..
        /// </summary>
        public static string Index_SubDescEnd {
            get {
                return ResourceManager.GetString("Index_SubDescEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a list of members currently attending the.
        /// </summary>
        public static string Index_SubDescStart {
            get {
                return ResourceManager.GetString("Index_SubDescStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Members.
        /// </summary>
        public static string Index_SubTitle {
            get {
                return ResourceManager.GetString("Index_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Members.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Index_User {
            get {
                return ResourceManager.GetString("Index_User", resourceCulture);
            }
        }
    }
}
