//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Groups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Groups() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Groups", typeof(Groups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create_BTN_Create {
            get {
                return ResourceManager.GetString("Create_BTN_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Create_BTN_Exit {
            get {
                return ResourceManager.GetString("Create_BTN_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group creation will have 3 parts: Creating the group, setting skillgoals for the group, and adding users to it..
        /// </summary>
        public static string Create_Desc1 {
            get {
                return ResourceManager.GetString("Create_Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can abort the process at any point (for example, if you don&apos;t want to add skillgoals or users right away) and the group will still be created..
        /// </summary>
        public static string Create_Desc2 {
            get {
                return ResourceManager.GetString("Create_Desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals and users can be added later..
        /// </summary>
        public static string Create_Desc3 {
            get {
                return ResourceManager.GetString("Create_Desc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to group creation!.
        /// </summary>
        public static string Create_SubTitle {
            get {
                return ResourceManager.GetString("Create_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups [1/3].
        /// </summary>
        public static string Create_Title {
            get {
                return ResourceManager.GetString("Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Edit_BTN_Save {
            get {
                return ResourceManager.GetString("Edit_BTN_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Group.
        /// </summary>
        public static string Edit_Title {
            get {
                return ResourceManager.GetString("Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Index_BTN_Create {
            get {
                return ResourceManager.GetString("Index_BTN_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Index_BTN_Search {
            get {
                return ResourceManager.GetString("Index_BTN_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Index_Group {
            get {
                return ResourceManager.GetString("Index_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for user groups....
        /// </summary>
        public static string Index_Search {
            get {
                return ResourceManager.GetString("Index_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add, edit, and view groups from here. Be careful, as deleting a user group will also remove any skillgoals for the users belonging to said group..
        /// </summary>
        public static string Index_SubDesc {
            get {
                return ResourceManager.GetString("Index_SubDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Groups.
        /// </summary>
        public static string Index_SubTitle {
            get {
                return ResourceManager.GetString("Index_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Groups.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Index_View {
            get {
                return ResourceManager.GetString("Index_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Members_Create_BTN_Submit {
            get {
                return ResourceManager.GetString("Members_Create_BTN_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Members.
        /// </summary>
        public static string Members_Create_Title {
            get {
                return ResourceManager.GetString("Members_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Members_Index_BTN_Delete {
            get {
                return ResourceManager.GetString("Members_Index_BTN_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Members_Index_BTN_Details {
            get {
                return ResourceManager.GetString("Members_Index_BTN_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Members.
        /// </summary>
        public static string Members_Index_BTN_EditMembers {
            get {
                return ResourceManager.GetString("Members_Index_BTN_EditMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Members_Index_BTN_Search {
            get {
                return ResourceManager.GetString("Members_Index_BTN_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for users....
        /// </summary>
        public static string Members_Index_Search {
            get {
                return ResourceManager.GetString("Members_Index_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members:.
        /// </summary>
        public static string Members_Index_SubDesc {
            get {
                return ResourceManager.GetString("Members_Index_SubDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of employees in.
        /// </summary>
        public static string Members_Index_SubTitle {
            get {
                return ResourceManager.GetString("Members_Index_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group ID.
        /// </summary>
        public static string MODEL_GroupID {
            get {
                return ResourceManager.GetString("MODEL_GroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupname.
        /// </summary>
        public static string MODEL_GroupName {
            get {
                return ResourceManager.GetString("MODEL_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MODEL_Name {
            get {
                return ResourceManager.GetString("MODEL_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string MODEL_UserID {
            get {
                return ResourceManager.GetString("MODEL_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string MODEL_UserName {
            get {
                return ResourceManager.GetString("MODEL_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Stats_BTN_Back {
            get {
                return ResourceManager.GetString("Stats_BTN_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Stats_BTN_Delete {
            get {
                return ResourceManager.GetString("Stats_BTN_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Stats_BTN_Edit {
            get {
                return ResourceManager.GetString("Stats_BTN_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string Stats_BTN_Goals {
            get {
                return ResourceManager.GetString("Stats_BTN_Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Stats_BTN_Members {
            get {
                return ResourceManager.GetString("Stats_BTN_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        public static string Stats_Goal {
            get {
                return ResourceManager.GetString("Stats_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals Updated:.
        /// </summary>
        public static string Stats_GoalsUpdated {
            get {
                return ResourceManager.GetString("Stats_GoalsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Average.
        /// </summary>
        public static string Stats_GroupAvg {
            get {
                return ResourceManager.GetString("Stats_GroupAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members:.
        /// </summary>
        public static string Stats_Members {
            get {
                return ResourceManager.GetString("Stats_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO_DATA.
        /// </summary>
        public static string Stats_NoData {
            get {
                return ResourceManager.GetString("Stats_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string Stats_Skill {
            get {
                return ResourceManager.GetString("Stats_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Statistics.
        /// </summary>
        public static string Stats_Title {
            get {
                return ResourceManager.GetString("Stats_Title", resourceCulture);
            }
        }
    }
}
