//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lessons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lessons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Lessons", typeof(Lessons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create_BTN_Create {
            get {
                return ResourceManager.GetString("Create_BTN_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Create_Date {
            get {
                return ResourceManager.GetString("Create_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Create_Hour {
            get {
                return ResourceManager.GetString("Create_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Create_Location {
            get {
                return ResourceManager.GetString("Create_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Create_Minute {
            get {
                return ResourceManager.GetString("Create_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Create_Name {
            get {
                return ResourceManager.GetString("Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a lesson.
        /// </summary>
        public static string Create_Title {
            get {
                return ResourceManager.GetString("Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attending.
        /// </summary>
        public static string MODEL_User_Attending {
            get {
                return ResourceManager.GetString("MODEL_User_Attending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson ID.
        /// </summary>
        public static string MODEL_User_LessonID {
            get {
                return ResourceManager.GetString("MODEL_User_LessonID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members ID.
        /// </summary>
        public static string MODEL_User_MemberID {
            get {
                return ResourceManager.GetString("MODEL_User_MemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Name.
        /// </summary>
        public static string MODEL_User_MemberName {
            get {
                return ResourceManager.GetString("MODEL_User_MemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string User_Create_BTN_Submit {
            get {
                return ResourceManager.GetString("User_Create_BTN_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Attendees.
        /// </summary>
        public static string User_Create_Title {
            get {
                return ResourceManager.GetString("User_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string User_Index_BTN_Create {
            get {
                return ResourceManager.GetString("User_Index_BTN_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string User_Index_BTN_Delete {
            get {
                return ResourceManager.GetString("User_Index_BTN_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string User_Index_BTN_Details {
            get {
                return ResourceManager.GetString("User_Index_BTN_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string User_Index_Title {
            get {
                return ResourceManager.GetString("User_Index_Title", resourceCulture);
            }
        }
    }
}
