//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced search.
        /// </summary>
        public static string Advanced_Search {
            get {
                return ResourceManager.GetString("Advanced_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select company.
        /// </summary>
        public static string CompaniesSelectDropdown {
            get {
                return ResourceManager.GetString("CompaniesSelectDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company is required.
        /// </summary>
        public static string CompanyRequired {
            get {
                return ResourceManager.GetString("CompanyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password!.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string CourseMem_Details_Completed {
            get {
                return ResourceManager.GetString("CourseMem_Details_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string CourseMem_Details_Course {
            get {
                return ResourceManager.GetString("CourseMem_Details_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a list of courses you have enrolled in or have completed in the past..
        /// </summary>
        public static string CourseMem_Details_Desc {
            get {
                return ResourceManager.GetString("CourseMem_Details_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your courses.
        /// </summary>
        public static string CourseMem_Details_DescTitle {
            get {
                return ResourceManager.GetString("CourseMem_Details_DescTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongoing.
        /// </summary>
        public static string CourseMem_Details_NotCompleted {
            get {
                return ResourceManager.GetString("CourseMem_Details_NotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string CourseMem_Details_Status {
            get {
                return ResourceManager.GetString("CourseMem_Details_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string CourseMem_Details_Title {
            get {
                return ResourceManager.GetString("CourseMem_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Dashboard_CourseCompleted {
            get {
                return ResourceManager.GetString("Dashboard_CourseCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongoing.
        /// </summary>
        public static string Dashboard_CourseNotComplete {
            get {
                return ResourceManager.GetString("Dashboard_CourseNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Dashboard_progress {
            get {
                return ResourceManager.GetString("Dashboard_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string DELETE_Back {
            get {
                return ResourceManager.GetString("DELETE_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE_Button {
            get {
                return ResourceManager.GetString("DELETE_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string DELETE_Desc {
            get {
                return ResourceManager.GetString("DELETE_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE_Title {
            get {
                return ResourceManager.GetString("DELETE_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Details_Table_Group {
            get {
                return ResourceManager.GetString("Details_Table_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Edit_SkillDesc {
            get {
                return ResourceManager.GetString("Edit_SkillDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid!.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email address is required!.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Employee_Create_Back {
            get {
                return ResourceManager.GetString("Employee_Create_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a new user, please fill the following information first..
        /// </summary>
        public static string Employee_Create_Desc {
            get {
                return ResourceManager.GetString("Employee_Create_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new user.
        /// </summary>
        public static string Employee_Create_DescTitle {
            get {
                return ResourceManager.GetString("Employee_Create_DescTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Employee_Create_Register {
            get {
                return ResourceManager.GetString("Employee_Create_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string Employee_Create_Title {
            get {
                return ResourceManager.GetString("Employee_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Groups.
        /// </summary>
        public static string Employee_Details_GroupTitle {
            get {
                return ResourceManager.GetString("Employee_Details_GroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Groups.
        /// </summary>
        public static string Employee_Edit_EGroups {
            get {
                return ResourceManager.GetString("Employee_Edit_EGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Roles.
        /// </summary>
        public static string Employee_Edit_ERoles {
            get {
                return ResourceManager.GetString("Employee_Edit_ERoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string Employee_Edit_NewPass {
            get {
                return ResourceManager.GetString("Employee_Edit_NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Employee_Edit_Save {
            get {
                return ResourceManager.GetString("Employee_Edit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Employee_Edit_Status {
            get {
                return ResourceManager.GetString("Employee_Edit_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new employee.
        /// </summary>
        public static string Employee_Index_Create {
            get {
                return ResourceManager.GetString("Employee_Index_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Employee_Index_Delete {
            get {
                return ResourceManager.GetString("Employee_Index_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Employee_Index_Details {
            get {
                return ResourceManager.GetString("Employee_Index_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Employee_Index_Edit {
            get {
                return ResourceManager.GetString("Employee_Index_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Employee_Index_Filter {
            get {
                return ResourceManager.GetString("Employee_Index_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for employees....
        /// </summary>
        public static string Employee_Index_SearchPholder {
            get {
                return ResourceManager.GetString("Employee_Index_SearchPholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Employee_Index_Status {
            get {
                return ResourceManager.GetString("Employee_Index_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee List.
        /// </summary>
        public static string Employee_Index_Title {
            get {
                return ResourceManager.GetString("Employee_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 - No interest.
        /// </summary>
        public static string EVAL_DROPDOWN_0 {
            get {
                return ResourceManager.GetString("EVAL_DROPDOWN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Apprentice.
        /// </summary>
        public static string EVAL_DROPDOWN_1 {
            get {
                return ResourceManager.GetString("EVAL_DROPDOWN_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Journeyman.
        /// </summary>
        public static string EVAL_DROPDOWN_2 {
            get {
                return ResourceManager.GetString("EVAL_DROPDOWN_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Expert.
        /// </summary>
        public static string EVAL_DROPDOWN_3 {
            get {
                return ResourceManager.GetString("EVAL_DROPDOWN_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Artisan.
        /// </summary>
        public static string EVAL_DROPDOWN_4 {
            get {
                return ResourceManager.GetString("EVAL_DROPDOWN_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 - Master.
        /// </summary>
        public static string EVAL_DROPDOWN_5 {
            get {
                return ResourceManager.GetString("EVAL_DROPDOWN_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is too long!.
        /// </summary>
        public static string FirstNameLong {
            get {
                return ResourceManager.GetString("FirstNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required!.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your email address where reset password link will be sent..
        /// </summary>
        public static string ForgotPassword_Desc {
            get {
                return ResourceManager.GetString("ForgotPassword_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Email has been sent to given E-mail address..
        /// </summary>
        public static string ForgotPassword_EmailSent {
            get {
                return ResourceManager.GetString("ForgotPassword_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string ForgotPassword_Submit {
            get {
                return ResourceManager.GetString("ForgotPassword_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPassword_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string GENERAL_Back {
            get {
                return ResourceManager.GetString("GENERAL_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string GENERAL_Search {
            get {
                return ResourceManager.GetString("GENERAL_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select group.
        /// </summary>
        public static string Group_Dropdownlist {
            get {
                return ResourceManager.GetString("Group_Dropdownlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select group.
        /// </summary>
        public static string groupDD_pick {
            get {
                return ResourceManager.GetString("groupDD_pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group member.
        /// </summary>
        public static string GroupMember_Delete_Name {
            get {
                return ResourceManager.GetString("GroupMember_Delete_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam mi nisl, varius non mauris ut, tristique pretium neque. Nam eu ante in tortor tincidunt cursus at sed nulla. Sed sed massa tempor, sagittis felis ac, consequat lacus. In vestibulum commodo ullamcorper. Curabitur vel aliquam ipsum, et tincidunt sapien. Duis molestie libero vitae ipsum venenatis ullamcorper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus nec orci lobortis, congue nunc non, por [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_Description_p1 {
            get {
                return ResourceManager.GetString("Home_Description_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proin volutpat arcu interdum finibus lacinia. Morbi vitae tellus venenatis lorem tincidunt cursus sit amet at orci. Aenean dui lacus, tempus eu ultricies at, tempor eu dolor. Aenean elit enim, pharetra nec aliquam et, porta nec nunc. Proin lacinia egestas vehicula. Proin eu volutpat sapien. Donec suscipit, sem eget hendrerit scelerisque, ex mi ullamcorper nunc, in maximus nunc mauris pellentesque lorem. Suspendisse ac lacinia dui, vel facilisis turpis. Nullam bibendum bibendum magna, suscipit semper ante co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_Description_p2 {
            get {
                return ResourceManager.GetString("Home_Description_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Category.
        /// </summary>
        public static string Index_BTN_CreateCategory {
            get {
                return ResourceManager.GetString("Index_BTN_CreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is too long!.
        /// </summary>
        public static string LastNameLong {
            get {
                return ResourceManager.GetString("LastNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required!.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Layout_Admin {
            get {
                return ResourceManager.GetString("Layout_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        public static string Layout_Certificates {
            get {
                return ResourceManager.GetString("Layout_Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string Layout_Courses {
            get {
                return ResourceManager.GetString("Layout_Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Layout_Employees {
            get {
                return ResourceManager.GetString("Layout_Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Layout_Groups {
            get {
                return ResourceManager.GetString("Layout_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGO_TBD.
        /// </summary>
        public static string Layout_Home {
            get {
                return ResourceManager.GetString("Layout_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Layout_Lang {
            get {
                return ResourceManager.GetString("Layout_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Layout_Login {
            get {
                return ResourceManager.GetString("Layout_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Layout_Logout {
            get {
                return ResourceManager.GetString("Layout_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Layout_Privacy {
            get {
                return ResourceManager.GetString("Layout_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Layout_Profile {
            get {
                return ResourceManager.GetString("Layout_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Layout_Roles {
            get {
                return ResourceManager.GetString("Layout_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Layout_Skills {
            get {
                return ResourceManager.GetString("Layout_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in with your email and password. If you have forgotten your password, click &quot;Forgot your password?&quot; link to get instructions..
        /// </summary>
        public static string Login_Desc {
            get {
                return ResourceManager.GetString("Login_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Avenla Employee Management System.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required!.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is too long!.
        /// </summary>
        public static string PhoneLong {
            get {
                return ResourceManager.GetString("PhoneLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Options.
        /// </summary>
        public static string Quick_Options {
            get {
                return ResourceManager.GetString("Quick_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give new password..
        /// </summary>
        public static string ResetPassword_Desc {
            get {
                return ResourceManager.GetString("ResetPassword_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed..
        /// </summary>
        public static string ResetPassword_PasswordChanged {
            get {
                return ResourceManager.GetString("ResetPassword_PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword_Submit {
            get {
                return ResourceManager.GetString("ResetPassword_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string ResetPassword_Title {
            get {
                return ResourceManager.GetString("ResetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select skill.
        /// </summary>
        public static string Skill_Dropdownlist {
            get {
                return ResourceManager.GetString("Skill_Dropdownlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string UCertificates_Create_Add {
            get {
                return ResourceManager.GetString("UCertificates_Create_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string UCertificates_Create_DateTitle {
            get {
                return ResourceManager.GetString("UCertificates_Create_DateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Certificate.
        /// </summary>
        public static string UCertificates_Create_DropDownDefault {
            get {
                return ResourceManager.GetString("UCertificates_Create_DropDownDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a certificate.
        /// </summary>
        public static string UCertificates_Create_Title {
            get {
                return ResourceManager.GetString("UCertificates_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string UCertificates_Index_Add {
            get {
                return ResourceManager.GetString("UCertificates_Index_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        public static string UCertificates_Index_Cert {
            get {
                return ResourceManager.GetString("UCertificates_Index_Cert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant Date.
        /// </summary>
        public static string UCertificates_Index_GrantDate {
            get {
                return ResourceManager.GetString("UCertificates_Index_GrantDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granted By.
        /// </summary>
        public static string UCertificates_Index_Granter {
            get {
                return ResourceManager.GetString("UCertificates_Index_Granter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for certificates....
        /// </summary>
        public static string UCertificates_Index_Search {
            get {
                return ResourceManager.GetString("UCertificates_Index_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Certificates.
        /// </summary>
        public static string UCertificates_Index_Title {
            get {
                return ResourceManager.GetString("UCertificates_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,.
        /// </summary>
        public static string User_Hello {
            get {
                return ResourceManager.GetString("User_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string UserSkills_Create_Submit {
            get {
                return ResourceManager.GetString("UserSkills_Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Evaluation.
        /// </summary>
        public static string UserSkills_Create_Title {
            get {
                return ResourceManager.GetString("UserSkills_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Level.
        /// </summary>
        public static string UserSkills_Edit_SkillLevel {
            get {
                return ResourceManager.GetString("UserSkills_Edit_SkillLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string UserSkills_Edit_Title {
            get {
                return ResourceManager.GetString("UserSkills_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generally, you should be creating a new evaluation instead of editing an existing one..
        /// </summary>
        public static string UserSkills_EditForm_Desc {
            get {
                return ResourceManager.GetString("UserSkills_EditForm_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit existing form.
        /// </summary>
        public static string UserSkills_EditForm_DescTitle {
            get {
                return ResourceManager.GetString("UserSkills_EditForm_DescTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Entries for:.
        /// </summary>
        public static string UserSkills_EditForm_Title {
            get {
                return ResourceManager.GetString("UserSkills_EditForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UserSkills_EditForm_Update {
            get {
                return ResourceManager.GetString("UserSkills_EditForm_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string UserSkills_ListByDate_Create {
            get {
                return ResourceManager.GetString("UserSkills_ListByDate_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string UserSkills_ListByDate_Date {
            get {
                return ResourceManager.GetString("UserSkills_ListByDate_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string UserSkills_ListByDate_Delete {
            get {
                return ResourceManager.GetString("UserSkills_ListByDate_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string UserSkills_ListByDate_Edit {
            get {
                return ResourceManager.GetString("UserSkills_ListByDate_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Type.
        /// </summary>
        public static string UserSkills_ListByDate_EvaluationType {
            get {
                return ResourceManager.GetString("UserSkills_ListByDate_EvaluationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X: day of the month, Y: SKill level. Hover on the point to reveal details.
        /// </summary>
        public static string UserSkills_ListByDate_GraphDesc {
            get {
                return ResourceManager.GetString("UserSkills_ListByDate_GraphDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill progression graph for the chosen date.
        /// </summary>
        public static string UserSkills_ListByDate_GraphTitle {
            get {
                return ResourceManager.GetString("UserSkills_ListByDate_GraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for dates....
        /// </summary>
        public static string UserSkills_ListByDate_SearchPHolder {
            get {
                return ResourceManager.GetString("UserSkills_ListByDate_SearchPHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Skill Overview.
        /// </summary>
        public static string UserSkills_ListByDate_Title {
            get {
                return ResourceManager.GetString("UserSkills_ListByDate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string UserSkills_ListByDate_View {
            get {
                return ResourceManager.GetString("UserSkills_ListByDate_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in Graph.
        /// </summary>
        public static string UserSkills_ListByDate_ViewGraph {
            get {
                return ResourceManager.GetString("UserSkills_ListByDate_ViewGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Average:.
        /// </summary>
        public static string UserSkills_SkillList_Average {
            get {
                return ResourceManager.GetString("UserSkills_SkillList_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Skill:.
        /// </summary>
        public static string UserSkills_SkillList_Best {
            get {
                return ResourceManager.GetString("UserSkills_SkillList_Best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate.
        /// </summary>
        public static string UserSkills_SkillList_Evaluate {
            get {
                return ResourceManager.GetString("UserSkills_SkillList_Evaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Goal.
        /// </summary>
        public static string UserSkills_SkillList_Goal {
            get {
                return ResourceManager.GetString("UserSkills_SkillList_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View History.
        /// </summary>
        public static string UserSkills_SkillList_History {
            get {
                return ResourceManager.GetString("UserSkills_SkillList_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Level.
        /// </summary>
        public static string UserSkills_SkillList_Level {
            get {
                return ResourceManager.GetString("UserSkills_SkillList_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Name.
        /// </summary>
        public static string UserSkills_SkillList_Name {
            get {
                return ResourceManager.GetString("UserSkills_SkillList_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Skills.
        /// </summary>
        public static string UserSkills_SkillList_Title {
            get {
                return ResourceManager.GetString("UserSkills_SkillList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worst Skill:.
        /// </summary>
        public static string UserSkills_SkillList_Worst {
            get {
                return ResourceManager.GetString("UserSkills_SkillList_Worst", resourceCulture);
            }
        }
    }
}
