//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SkillGoals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SkillGoals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SkillGoals", typeof(SkillGoals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Create_Add {
            get {
                return ResourceManager.GetString("Create_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Create_BTN_Next {
            get {
                return ResourceManager.GetString("Create_BTN_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Create_BTN_Submit {
            get {
                return ResourceManager.GetString("Create_BTN_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No skills created yet!.
        /// </summary>
        public static string Create_Error_NoSkills {
            get {
                return ResourceManager.GetString("Create_Error_NoSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Skill.
        /// </summary>
        public static string Create_SelectDropdown {
            get {
                return ResourceManager.GetString("Create_SelectDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Goal.
        /// </summary>
        public static string Create_SelectGoal {
            get {
                return ResourceManager.GetString("Create_SelectGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Goals.
        /// </summary>
        public static string Create_Title {
            get {
                return ResourceManager.GetString("Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal for.
        /// </summary>
        public static string Edit_Goal {
            get {
                return ResourceManager.GetString("Edit_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Edit_Save {
            get {
                return ResourceManager.GetString("Edit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Index_BTN_Create {
            get {
                return ResourceManager.GetString("Index_BTN_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Index_BTN_Delete {
            get {
                return ResourceManager.GetString("Index_BTN_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Index_BTN_Edit {
            get {
                return ResourceManager.GetString("Index_BTN_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        public static string Index_Goal {
            get {
                return ResourceManager.GetString("Index_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO GOAL.
        /// </summary>
        public static string Index_NoGoal {
            get {
                return ResourceManager.GetString("Index_NoGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string Index_SelectDropdown {
            get {
                return ResourceManager.GetString("Index_SelectDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string Index_Skill {
            get {
                return ResourceManager.GetString("Index_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals for.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string MODEL_Date {
            get {
                return ResourceManager.GetString("MODEL_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string MODEL_GroupName {
            get {
                return ResourceManager.GetString("MODEL_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Goal.
        /// </summary>
        public static string MODEL_SkillGoal {
            get {
                return ResourceManager.GetString("MODEL_SkillGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Name.
        /// </summary>
        public static string MODEL_SkillName {
            get {
                return ResourceManager.GetString("MODEL_SkillName", resourceCulture);
            }
        }
    }
}
