//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Skills {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Skills() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Skills", typeof(Skills).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create_Submit {
            get {
                return ResourceManager.GetString("Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new skill.
        /// </summary>
        public static string Create_Title {
            get {
                return ResourceManager.GetString("Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string Delete_Skill {
            get {
                return ResourceManager.GetString("Delete_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Edit_BTN_Submit {
            get {
                return ResourceManager.GetString("Edit_BTN_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Edit_SkillDesc {
            get {
                return ResourceManager.GetString("Edit_SkillDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Name.
        /// </summary>
        public static string Edit_SkillName {
            get {
                return ResourceManager.GetString("Edit_SkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Skill.
        /// </summary>
        public static string Edit_Title {
            get {
                return ResourceManager.GetString("Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Index_BTN_Create {
            get {
                return ResourceManager.GetString("Index_BTN_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Category.
        /// </summary>
        public static string Index_BTN_CreateCategory {
            get {
                return ResourceManager.GetString("Index_BTN_CreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Index_BTN_Delete {
            get {
                return ResourceManager.GetString("Index_BTN_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Index_BTN_Details {
            get {
                return ResourceManager.GetString("Index_BTN_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Index_BTN_Edit {
            get {
                return ResourceManager.GetString("Index_BTN_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Index_BTN_Search {
            get {
                return ResourceManager.GetString("Index_BTN_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for skills....
        /// </summary>
        public static string Index_Search {
            get {
                return ResourceManager.GetString("Index_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string Index_Skill {
            get {
                return ResourceManager.GetString("Index_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are listed all the skills that can be set as goals for different user groups. You can add, remove, and edit them here.
        ///                If you want to edit skill goals for users, go to.
        /// </summary>
        public static string Index_SubDesc {
            get {
                return ResourceManager.GetString("Index_SubDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groups..
        /// </summary>
        public static string Index_SubLink {
            get {
                return ResourceManager.GetString("Index_SubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of skills.
        /// </summary>
        public static string Index_SubTitle {
            get {
                return ResourceManager.GetString("Index_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string MODEL_Skill {
            get {
                return ResourceManager.GetString("MODEL_Skill", resourceCulture);
            }
        }
    }
}
